### ISSUE TITLE
error

### ISSUE THREAD

**Issue by taki0112** [rorodata/background-removal#3]
```
Traceback (most recent call last):
  File "test.py", line 26, in <module>
    main()
  File "test.py", line 16, in main
    new_image = background_removal.predict(image_file=open(image_path, 'rb'), format=format)
  File "C:\anaconda\envs\junho\lib\site-packages\firefly\client.py", line 116, in wrapped
    return client.call_func(func_name, **kwargs)
  File "C:\anaconda\envs\junho\lib\site-packages\firefly\client.py", line 21, in call_func
    return self.request(path, **kwargs)
  File "C:\anaconda\envs\junho\lib\site-packages\firefly\client.py", line 38, in request
    return self.handle_response(response)
  File "C:\anaconda\envs\junho\lib\site-packages\firefly\client.py", line 97, in handle_response
    raise ValidationError(response.json()["error"])
firefly.validator.ValidationError: missing a required argument: 'image'
```

missing a required argument : 'image' ...
help me plz !

**Comment by SUYONGJIAN** [comment]
have you resolved that problem？
