### ISSUE TITLE
error

### ISSUE THREAD

**Issue by SUYONGJIAN** [rorodata/background-removal#4]
calling the background removal API...
Traceback (most recent call last):
  File ".\bgremove.py", line 23, in <module>
    main()
  File ".\bgremove.py", line 12, in main
    new_image = background_removal.predict(image_file=open(image_path, 'rb'), format=format)
  File "C:\Python35\lib\site-packages\firefly\client.py", line 100, in wrapped
    return client.call_func(func_name, **kwargs)
  File "C:\Python35\lib\site-packages\firefly\client.py", line 17, in call_func
    return self.request(path, **kwargs)
  File "C:\Python35\lib\site-packages\firefly\client.py", line 30, in request
    return self.handle_response(response)
  File "C:\Python35\lib\site-packages\firefly\client.py", line 83, in handle_response
    raise ValidationError(response.json()["error"])
firefly.validator.ValidationError: missing a required argument: 'image'

**Comment by waallf** [comment]
I have the same issue.Have you resolved the issue?

**Comment by juno249** [comment]
i got the same issue as you

**Comment by nanthakumar94** [comment]
i got the same issue. have you resolved the issue? @waallf  and @juno249

**Comment by Pinkman026** [comment]
same issue.
